import { TypographyH1 } from "@/components/ui/typography-h1";
import { TypographyH2 } from "@/components/ui/typography-h2";
import { TypographyP } from "@/components/ui/typography-p";
import Link from "next/link";

export default function Terms() {
  return (
    <>
      <TypographyH1 className="border-b-6 mb-6 border-black pb-4 lg:pb-8">
        Terms and Conditions
      </TypographyH1>

      <section className="mt-10 space-y-16">
        <div className="space-y-6">
          <TypographyH2>1. Acceptance of Terms:</TypographyH2>
          <TypographyP>
            By utilizing the services provided by CVONCALL Career Services
            Private Limited (&quot;COC&quot;), hereinafter referred to as
            &quot;the Company,&quot; you acknowledge and agree to abide by the
            terms and conditions outlined in this document. These terms
            constitute a legally binding agreement between you and the Company.
          </TypographyP>
        </div>
        <div className="space-y-6">
          <TypographyH2>2. Service Description:</TypographyH2>
          <TypographyP>
            The Company offers CV generation & other career services wherein
            candidates provide their personal and professional information, and
            the Company, utilizing the technology, generates a professionally
            crafted Curriculum Vitae (CV) within a specified time frame.
          </TypographyP>
        </div>
        <div className="space-y-6">
          <TypographyH2>3. User Responsibilities:</TypographyH2>
          <TypographyP>
            <strong>a.</strong> You are responsible for providing accurate and
            up-to-date information during the CV creation process.
          </TypographyP>
          <TypographyP>
            <strong>b.</strong> You must ensure the security of your login
            credentials and notify the Company immediately of any unauthorized
            access to your account.
          </TypographyP>
          <TypographyP>
            <strong>c.</strong> You must ensure a good internet speed (ideally,
            10 to 15 MBps) while you apply for CV generation in order to get the
            technology to work effectively.
          </TypographyP>
        </div>
        <div className="space-y-6">
          <TypographyH2>4. CV Delivery:</TypographyH2>
          <TypographyP>
            <strong>a.</strong> The Company commits to delivering the generated
            CV within the specified time frame, provided accurate information is
            supplied by the user.
          </TypographyP>
          <TypographyP>
            <strong>b.</strong> In the event of any unforeseen technical issues
            or delays, the Company will make reasonable efforts to rectify the
            situation promptly.
          </TypographyP>
        </div>
        <div className="space-y-6">
          <TypographyH2>5. Data Privacy:</TypographyH2>
          <TypographyP>
            <strong>a.</strong> The Company respects user privacy and is
            committed to safeguarding personal information. Please refer to our{" "}
            <Link href="/privacy" className="underline">
              Privacy Policy
            </Link>{" "}
            for details on data handling practices.
          </TypographyP>
        </div>
        <div className="space-y-6">
          <TypographyH2>6. Intellectual Property:</TypographyH2>
          <TypographyP>
            <strong>a.</strong> The CV generated by the Company is the
            intellectual property of the user.
          </TypographyP>
          <TypographyP>
            <strong>b.</strong> The Company retains the right to use anonymized
            and aggregated data for research and improvement purposes.
          </TypographyP>
        </div>
        <div className="space-y-6">
          <TypographyH2>7. Service Modifications:</TypographyH2>
          <TypographyP>
            The Company reserves the right to modify, suspend, or discontinue
            any aspect of the service, including these terms, at its sole
            discretion. Users will be notified of significant changes.
          </TypographyP>
        </div>
        <div className="space-y-6">
          <TypographyH2>8. Limitation of Liability:</TypographyH2>
          <TypographyP>
            The Company shall not be liable for any direct, indirect,
            incidental, special, or consequential damages resulting from the use
            or inability to use the service.
          </TypographyP>
        </div>
        <div className="space-y-6">
          <TypographyH2>9. Refund Policy:</TypographyH2>
          <TypographyP>
            Please refer to our{" "}
            <Link href="/refund" className="underline">
              Refund Policy
            </Link>{" "}
            for information on refunds related to service delivery.
          </TypographyP>
        </div>
        <div className="space-y-6">
          <TypographyH2>10. Governing Law:</TypographyH2>
          <TypographyP>
            These terms and conditions are governed by the laws of Lucknow
            Jurisdiction, and any disputes arising under or in connection with
            these terms shall be subject to the exclusive jurisdiction of the
            courts located in Lucknow.
          </TypographyP>
          <TypographyP>
            By using the services of CVONCALL Career Services Private Limited
            (&quot;COC&quot;), you acknowledge that you have read, understood,
            and agreed to these terms and conditions. If you do not agree with
            any part of these terms, you may not use the Company&apos;s
            services.
          </TypographyP>
        </div>
      </section>
    </>
  );
}
